### ISSUE TITLE
can't install on fresh volumio 3.324

### ISSUE THREAD

**Issue by karba78** [Saiyato/volumio-snapclient-plugin#11] opened 2022-07-19 18:46 UTC
server modules installs fine
client module starts fine but does not finish
only spotify and server are installed as plugins
is it necessary like in the past to install client and server on the server
thks

 ================================ WARNING ====================================
 
This plugin is not verified by Volumio. Installing it is UNSAFE and can make your system UNSTABLE!
You are STRONGLY advised not to install plugins manually, better wait they are officially available.
 
 =============================================================================
? Do you want to install this plugin anyway? Yes
Compressing the plugin
No modules found, running "npm install"
npm notice created a lockfile as package-lock.json. You should commit this file.
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
nloading plugin at http://127.0.0.1:3000/plugin-serve/snapclient.zip
Progress: 30
Status :Creating install location
Creating install location
Progress: 40
Status :Unpacking plugin
Unpacking plugin
Progress: 45
Status :Checking that the plugin is suitable for this version of Volumio The plugin can be used with this version of Volumio
Checking that the plugin is suitable for this version of Volumio The plugin can be used with this version of Volumio
Progress: 50
Status :Checking for duplicate plugin
Checking for duplicate plugin
Progress: 60
Status :Copying plugin to location
Copying plugin to location
Progress: 70
Status :Installing necessary utilities
Installing necessary utilities
Progress: 70
Status :Installing necessary utilities
Installing SnapClient and dependencies...
Progress: 0
Status :An error occurred while installing the plugin Error
An error occurred while installing the plugin Error
Failed to Install Plugin

**Comment by anLizard** [comment] 2022-07-22 07:55
Experiencing the same problem. Here is the live log from installation:

```
Starting Live Log...
info: CoreStateMachine::getQueue
info: CorePlayQueue::getQueue
info: CoreCommandRouter::executeOnPlugin: system , getHwuuid
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
info: Listing playlists
info: Listing playlists
info: CALLMETHOD: system_controller system enableLiveLog true
info: CoreCommandRouter::executeOnPlugin: system , enableLiveLog
info: Launching a new LiveLog session
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0

info: Downloading plugin at http://127.0.0.1:3000/plugin-serve/snapclient.zip
info: END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/snapclient.zip
info: Folder /tmp/plugins removed
info: Check plugin dependencies
info: CoreCommandRouter::executeOnPlugin: system , getSystemVersion
info: Checking if plugin already exists
info: Rename folder
info: Folder /tmp/downloaded_plugin.zip removed
info: Move to category
info: Checking if install.sh is present
info: Executing install.sh
 volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/sh /data/plugins/audio_interface/snapclient/install.sh
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
info: Installing SnapClient and dependencies...
info: Installing SnapClient and dependencies...
info: Install script return the error Error: Command failed: echo volumio | sudo -S sh /data/plugins/audio_interface/snapclient/install.sh > /tmp/installog
[sudo] password for volumio: /data/plugins/audio_interface/snapclient/install.sh: 81: /data/plugins/audio_interface/snapclient/install.sh: Syntax error: end of file unexpected (expecting "fi")
info: An error occurred installing the plugin. Rolling back config
info: Plugin folders cleanup
info: Scanning into folder /volumio/app/plugins/
info: Scanning category audio_interface
info: Scanning category miscellanea
info: Scanning category music_service
info: Scanning category plugins.json
info: Scanning category system_controller
info: Scanning category user_interface
info: Scanning into folder /data/plugins/
info: Scanning category audio_interface
info: Scanning category music_service
info: Scanning category user_interface
info: Plugin folders cleanup completed
info: Error: Error
info: Folder /tmp/plugins removed
info: Folder /tmp/downloaded_plugin.zip removed
info: Folder /data/temp removed
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
info: Listing playlists
info: Listing playlists
process exited with code null

```

**Comment by karba78** [comment] 2022-07-22 08:18
managed to get the system functional (even with install errror) by
- fresh volumio install
- install client
- install server
- install spotify
got an error as above with client install but system is functional
hope it helps

**Comment by anLizard** [comment] 2022-07-22 08:28
Thank you @karba78, I tried it but could not get it to work, sadly.

After installation with the error, when activating the snapclient plugin: 
![image](https://user-images.githubusercontent.com/48686356/180397663-91491d31-3572-4ad3-af0e-8a02f012ddce.png)

And when changing any settings in the snapclient plugin:
![image](https://user-images.githubusercontent.com/48686356/180397768-a86b6257-080d-4b57-b0f2-6d30ee76c836.png)

Also, when the plugin is active, there is no sound when I play Spotify.

**Comment by karba78** [comment] 2022-07-22 08:43
did the same to me if i installed the client after spotity and the server, but install client first on fresh install and then server and then spotify did the trick

**Comment by karba78** [comment] 2022-07-23 15:39
thank's saiyato, just tried on a fresh 3.324 with no plugin installed your last commit
same issue as above; client is not installing. thks for trying

**Comment by Saiyato** [comment] 2022-07-25 08:45
Weird, I'll try to test a bit more tonight; it makes no sense. Thanks for trying the quick commit :wink:
You did install from the dev-branch, right? It's not yet pushed to main

**Comment by anLizard** [comment] 2022-07-25 10:06
I tried by git cloning the dev branch and doing `Volumio plugin install`, and the install from zip plugin, but think I didn't get on the right path.

Not at home right now so can't give you logs, sadly.

Can you provide instructions how to properly install from dev branch?

**Comment by Saiyato** [comment] 2022-07-25 15:45
I've prepped a script for lazy installation (a long time ago), you can just use it with the following command `./volumio_install_from_zip.sh Saiyato volumio-snapclient-plugin development`

Script can be found here: https://github.com/Saiyato/volumio-plugin-helper; download it: `sudo wget -O volumio_install_from_zip.sh https://raw.githubusercontent.com/Saiyato/volumio-plugin-helper/master/volumio_install_from_zip.sh && sudo chmod +x volumio_install_from_zip.sh`

**Comment by Saiyato** [comment] 2022-07-25 15:51
Just merged it to main, because I confirmed it to be working now. Plugin installs and service starts, whereas the previous version failed on both accounts.

**Closed as completed** 2022-07-25 15:50 UTC

**Comment by anLizard** [comment] 2022-07-25 16:26
I was able to install now :)
Thank you so much for all the work you are putting into these plugins!!

**Comment by karba78** [comment] 2022-07-27 07:13
hello Saiyato , many thank's it does install perfectly now. but the sound is weird. the output comes completely scrambled if I have the client installed on the server. if I have only server running on my source; all other satellites play well. If I run the client on the server all sync is wrong, like if the client installed on the server was messing the flow or the synchro

**Comment by alamoudimoh** [comment] 2023-09-09 16:02
> hello Saiyato , many thank's it does install perfectly now. but the sound is weird. the output comes completely scrambled if I have the client installed on the server. if I have only server running on my source; all other satellites play well. If I run the client on the server all sync is wrong, like if the client installed on the server was messing the flow or the synchro

i have exactly the same 

installed it through the following commands:

```
sudo wget -O volumio_install_from_zip.sh https://raw.githubusercontent.com/Saiyato/volumio-plugin-helper/master/volumio_install_from_zip.sh && sudo chmod +x volumio_install_from_zip.sh


./volumio_install_from_zip.sh Saiyato volumio-snapserver-plugin

./volumio_install_from_zip.sh Saiyato volumio-snapclient-plugin
```
once installed i cannot access the server plugin, when i click on setting it takes me back to homepage
